identifier_name:
  excluded:
    - id

included:
  - Provbit

excluded:
  - Provbit/Application/ProvbitKeys.swift
  - Provbit/MokoKSwift/*
  - ./vendor

opt_in_rules:
  - file_header

disabled_rules:
  - multiple_closures_with_trailing_closure

trailing_comma:
  mandatory_comma: true
file_header:
   forbidden_pattern: "[^\n]"

warning_threshold: 1
